services:
  elasticsearch:
    build: .
    container_name: vinshop-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - /home/vingerchan/esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock: { soft: -1, hard: -1 }

  tracker:
    image: delron/fastdfs
    container_name: tracker
    network_mode: host
    restart: always
    command: tracker
    volumes:
      - /home/vingerchan/fdfs/tracker:/var/fdfs

  storage:
    image: delron/fastdfs
    container_name: storage
    network_mode: host
    restart: always
    command: storage
    environment:
      - TRACKER_SERVER=192.168.233.128:22122
    volumes:
      - /home/vingerchan/fdfs/storage:/var/fdfs