"""
Django settings for VinShop project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path

from django.conf.global_settings import AUTH_USER_MODEL
AUTH_USER_MODEL = 'users.User'   # 重写登陆通过这个模型

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 读取项目根目录的 .env（不进 git），把其中的键值注入 os.environ
def _load_env():
    env_file = BASE_DIR / '.env'
    if not env_file.exists():
        return
    for line in env_file.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        os.environ.setdefault(key.strip(), value.strip())

_load_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.users',
    'apps.verifications',
    'apps.areas',
    'apps.goods',
    'apps.browse',
    'apps.carts',
    'apps.orders',
    'apps.payment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VinShop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VinShop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', ''),
        'NAME': 'VinShop',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'Zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
    JWT 的验证，不是“查数据库”，而是“验签名 + 读内容”
"""
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES':(
        'rest_framework.permissions.AllowAny',
    )
}
from datetime import timedelta
"""
    登录，服务端返回了access token(有效期一天)和 refresh token(有效期一个月)，如果假设一个月都是登录状态，不logout，那么在这期间，就生成了30个不同的access token，但是不会让我强制下线，但是如果30天一到，refresh token过期了，就不会生成access token，那么这个时候access token过期也过期了之后 ，服务端检测不到access token，就会判定未登录，强制让我重新登录
    """
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME' : timedelta(minutes=15),    # 设置 Access Token（访问令牌）的有效期
    'REFRESH_TOKEN_LIFETIME' : timedelta(days=1),   # 设置 Refresh Token（刷新令牌）的有效期,决定用户 多久需要重新登录一次,一般比ACCESS TOKEN长很多
}

# 容联云API设置
RONGLIAN_ACC_ID = os.environ.get('RONGLIAN_ACC_ID', '')
RONGLIAN_ACC_TOKEN = os.environ.get('RONGLIAN_ACC_TOKEN', '')
RONGLIAN_APP_ID = os.environ.get('RONGLIAN_APP_ID', '')
RONGLIAN_SMS_TEMPLATE_ID = '1'

# Django Cache
CACHES = {
    'default': {        # 默认
        'BACKEND':'django_redis.cache.RedisCache',
        'LOCATION':'redis://127.0.0.1:6379/0',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'code' : {          # 保存验证码(图形，短信)
        'BACKEND':'django_redis.cache.RedisCache',
        'LOCATION':'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'history' : {       # 浏览记录
        'BACKEND':'django_redis.cache.RedisCache',
        'LOCATION':'redis://127.0.0.1:6379/2',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'carts' : {         # 购物车
        'BACKEND':'django_redis.cache.RedisCache',
        'LOCATION':'redis://127.0.0.1:6379/3',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'orders' : {        # 订单
        'BACKEND' : 'django_redis.cache.RedisCache',
        'LOCATION' : 'redis://127.0.0.1:6379/4',
        'OPTIONS' : {
            'CLIENT_CLASS' : 'django_redis.client.DefaultClient',
        }
    }
}

FDFS_BASE_URL = 'http://192.168.233.128:8888/'
FDFS_CLIENT_CONF={
    'host_tuple':('192.168.233.128',),
    'port':22122,
    'timeout':30,
    'tracker_pool_size':10
}

# 邮箱配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '2741232639@qq.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# 推荐商品限制个数
POPULAR_POOL = 50
POPULAR_LIMIT = 15

# ElasticSearch 商品搜索
ES_HOST = 'http://localhost:9200'
# 索引名，全项目统一从这里取，避免到处写死字符串。索引名全小写是ES硬性要求
ES_SKU_INDEX = 'sku'

# 浏览记录
BROWSING_DAYS = 7       # 只保留近七天
BROWSING_LIMIT = 200    # 单个用户最多保留200条

# 运费计算
FREE_FREIGHT_LIMIT = Decimal('69.00')
FREIGHT = Decimal('10.00')

os.makedirs(BASE_DIR/'logs',exist_ok=True)
LOGGING = {
    'version': 1,    # 配置格式版本号
    'disable_existing_loggers': False,    # 不禁用已存在的logger
    'formatters': {    # 格式器：定义"日志长什么样"
        'verbose': {
            'format' : '{asctime} [{levelname}] {name}:{lineno} - {message}',
            'style': '{',
        }
    },
    'handlers' : {    # 处理器：定义"日志输出到哪"
        # 处理器名字
        'order_file' : {
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : str(BASE_DIR/'logs/order.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 5,    # 备份多少个文件
            'encoding': 'utf-8',
            'formatter': 'verbose',
        }
    },
    'loggers' : {    # 记录器
        'apps.orders' : {
            'handlers': ['order_file'],
            'level' : 'WARNING',
            'propagate': False,
        },
    },
}